name: 02 - Stages
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Simulating build..."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Simulating test after build."
